name: Automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches: [ master ]
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.8'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: |
        python -m unittest -v tests/test_persona.py
    - name: Validar resultado con errores
      if: ${{ failure() }}
      uses: superbrothers/close-pull-request@v3
      with:
        comment: "Pull request cerrado debido a que las pruebas unitarias fallaron."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Validar resultado sin errores
      if: ${{ success() }}
      uses: kentaro-m/auto-assign-action@v1.1.2
      with:
        configuration-path: ".github/some_name_for_configs.yml"
    - name: Cálculo de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m unittest tests/test_persona.py
          coverage report -m